#!/usr/bin/env bash
# prints /etc/passwd content formmated to a string

while IFS=':' read -r un pass id gid inf homeD sh;
do
  echo "The user $un is part of the $gid gang,"\
  "lives in $homeD and rides $sh."\
  "$id's place is protected by the passcode $pass,"\
  "more info about the user here: $inf"
done < "/etc/passwd"
